<?php
/**
 * @package      Webcode_Glami
 *
 * @author       Kostadin Bashev (bashev@webcode.bg)
 * @copyright    Copyright © 2020 Webcode Ltd. (https://webcode.bg/)
 * @license      See LICENSE.txt for license details.
 */
?>
<?php if (($event = $block->getEventName()) && ($data = $block->getEventData()) && $block->isPixelEnabled()) : ?>
    <script>
        glami('track', '<?php echo $event; ?>', <?php echo $data; ?>);
    </script>
<?php else : ?>
    <div data-role="glami-event" style="display:none;"></div>
    <script type="text/x-magento-init">
        {"[data-role='glami-event']": {"Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>}}
    </script>
<?php endif; ?>
