<?php
/*
 * @package      Webcode_Glami
 *
 * @author       Kostadin Bashev (bashev@webcode.bg)
 * @copyright    Copyright © 2021 Webcode Ltd. (https://webcode.bg/)
 * @license      See LICENSE.txt for license details.
 */

/** @var \Webcode\Glami\Block\Pixel $block */
?>
<?php if (($event = $block->getEventName()) && ($block->isPixelEnabled() && $data = $block->getEventData())):?>
    <script>
        glami('track', '<?= /** @noEscape */ $event ?>', <?= /** @noEscape */ $data ?>);
    </script>
<?php else:?>
    <div data-role="glami-event" style="display:none;"></div>
    <script type="text/x-magento-init">
        {"[data-role='glami-event']": {"Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>}}
    </script>
<?php endif ?>
