<?php
/*
 * @package      Webcode_Glami
 *
 * @author       Webcode, Kostadin Bashev (bashev@webcode.bg)
 * @copyright    Copyright © 2021 GLAMI Inspigroup s.r.o.
 * @license      See LICENSE.txt for license details.
 */

/** @var \Webcode\Glami\Block\Pixel $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if (($event = $block->getEventName()) && ($block->isPixelEnabled() && $data = $block->getEventData())):?>
    <script>
        glami('track', '<?= $escaper->escapeJs($event) ?>', <?= /** @noEscape */ $data ?>);
    </script>
<?php else:?>
    <div data-role="glami-event" style="display:none;"></div>
    <script type="text/x-magento-init">
        {"[data-role='glami-event']": {"Magento_Ui/js/core/app": <?= /** @noEscape */ $block->getJsLayout() ?>}}
    </script>
<?php endif ?>
