<?php
/*
 * @package      Webcode_Glami
 *
 * @author       Webcode, Kostadin Bashev (bashev@webcode.bg)
 * @copyright    Copyright © 2021 GLAMI Inspigroup s.r.o.
 * @license      See LICENSE.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/** @var \Magento\Backend\Block\Template $block */

$_htmlId = $block->getHtmlId() ?: '_' . uniqid('', true);
?>
<?php if ($block->getGlamiCategoryRenderer()->canRenderCategories()): ?>
    <div class="design_theme_ua_regexp" id="grid<?= $block->escapeHtmlAttr($_htmlId) ?>">
        <div class="admin__control-table-wrapper">
            <table class="admin__control-table" id="<?= $block->escapeHtmlAttr($block->getElement()->getId()) ?>">
                <thead>
                <tr>
                    <?php foreach ($block->getColumns() as $columnName => $column): ?>
                        <th style="width:50%"><?= $block->escapeHtml($column['label']) ?></th>
                    <?php endforeach ?>
                </tr>
                </thead>
                <tbody id="addRow<?= $block->escapeHtmlAttr($_htmlId) ?>">
                <?php foreach ($block->getArrayRows() as $_rowId => $_row): ?>
                <tr>
                    <td>
                       <input type="hidden" id="<?= $block->escapeHtmlAttr($_rowId) ?>_source_id"
                       name="groups[feed][fields][categories][value][<?= $block->escapeHtml($_rowId) ?>][source_id]"
                           value="<?= $block->escapeHtml($_row->getData('source_id')) ?>"
                           readonly="readonly"/>
                       <input type="text" id="<?= $block->escapeHtml($_rowId) ?>_source"
                           name="groups[feed][fields][categories][value][<?= $block->escapeHtml($_rowId) ?>][source]"
                           title="<?= $block->escapeHtml($_row->getData('source')) ?>"
                           value="<?= $block->escapeHtml($_row->getData('source')) ?>"
                           class="input-text" readonly="readonly"/>
                    </td>
                    <td>
                        <?= /* @noEscape */
                        str_replace('<%- _id %>', $_rowId, $block->renderCellTemplate('target')) ?>
                        <script>
                            require(['jquery'], function ($) {
                                $('#<?= $block->escapeHtmlAttr($_rowId)?>_target')
                                    .val('<?= $block->escapeHtmlAttr($_row->getData('target')) ?>');
                            })
                        </script>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <input type="hidden" name="<?= $block->escapeHtmlAttr($block->getElement()->getName()) ?>[__empty]" value=""/>
    </div>
<?php else: ?>
    <button type="submit" id="save-glami-config" class="action-default scalable save primary ui-button ui-widget
    ui-state-default ui-corner-all ui-button-text-only"><?= $block->escapeHtml(__('Save Config')) ?></button>
    <small><?= $block->escapeHtml(__('Categories will be displayed after save configuration with Locale.')) ?></small>
<?php endif ?>
